apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-api-deployment
  labels:
    app: tiny-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiny-api
  template:
    metadata:
      labels:
        app: tiny-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: tiny-api
        image: tiny-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: WELCOME_PREFIX
          value: "Bem-vindo(a) via K8s"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://my-signoz-otel-collector.platform.svc.cluster.local:4318"
        - name: OTEL_SERVICE_NAME
          value: "tiny-api-service"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"